In [2]:
import numpy as np

In [3]:
# 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
vector_nat = np.arange(1, 21)
print(vector_nat)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
# 2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
matrix_ones = np.ones((4, 4))
print(matrix_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
matrix_rand_5x5 = np.random.uniform(-1, 1, (5, 5))
print(matrix_rand_5x5)

[[ 0.00821973  0.26918159  0.11718722 -0.0397528   0.69927973]
 [-0.91931923 -0.66048065 -0.27682396  0.19214234  0.13941452]
 [-0.9267396   0.79128303  0.41869781 -0.92422577 -0.40279088]
 [ 0.92052878  0.02803256 -0.07049617 -0.69420541  0.854351  ]
 [ 0.86478878  0.31453784 -0.03505053 -0.17284029  0.42229874]]


In [6]:
# 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix_rand_3x3 = np.random.rand(3, 3)
print(matrix_rand_3x3)

[[0.09167119 0.27553397 0.70295072]
 [0.65827569 0.86531894 0.52770037]
 [0.07705734 0.77062236 0.52032175]]


In [7]:
# 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.
arr1 = np.random.randint(1, 21, 6)
arr2 = np.random.randint(1, 21, 6)

print(f"Масив 1: {arr1}")
print(f"Масив 2: {arr2}")
print(f"Додавання: {arr1 + arr2}")
print(f"Віднімання: {arr1 - arr2}")
print(f"Множення:  {arr1 * arr2}")

Масив 1: [ 3  1 15  8  1  8]
Масив 2: [ 2  2  9 15  9 15]
Додавання: [ 5  3 24 23 10 23]
Віднімання: [ 1 -1  6 -7 -8 -7]
Множення:  [  6   2 135 120   9 120]


In [8]:
# 6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 5 та перемножте їх між собою.
mat_a = np.random.randint(1, 6, (3, 2))
mat_b = np.random.randint(1, 6, (2, 4))
res_dot = np.dot(mat_a, mat_b)

print("Матриця 3x2:\n", mat_a)
print("Матриця 2x4:\n", mat_b)
print("Результат множення:\n", res_dot)

Матриця 3x2:
 [[1 2]
 [4 2]
 [5 3]]
Матриця 2x4:
 [[1 3 5 4]
 [5 1 1 3]]
Результат множення:
 [[11  5  7 10]
 [14 14 22 22]
 [20 18 28 29]]


In [9]:
# 7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
mat_trans = np.random.rand(3, 3)
print("Оригінальна матриця:\n", mat_trans)
print("Транспонована матриця:\n", mat_trans.T)

Оригінальна матриця:
 [[0.50180553 0.61112223 0.21663888]
 [0.9827931  0.9599013  0.92125365]
 [0.23892872 0.03947283 0.28879597]]
Транспонована матриця:
 [[0.50180553 0.9827931  0.23892872]
 [0.61112223 0.9599013  0.03947283]
 [0.21663888 0.92125365 0.28879597]]


In [10]:
# 8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 10 та знайдіть їхню різницю.
mat_m1 = np.random.randint(1, 11, (3, 3))
mat_m2 = np.random.randint(1, 11, (3, 3))

print("Матриця 1:\n", mat_m1)
print("Матриця 2:\n", mat_m2)
print("Різниця:\n", mat_m1 - mat_m2)

Матриця 1:
 [[6 3 7]
 [3 8 6]
 [8 6 2]]
Матриця 2:
 [[10 10  9]
 [ 2 10  3]
 [ 3  2  6]]
Різниця:
 [[-4 -7 -2]
 [ 1 -2  3]
 [ 5  4 -4]]


In [11]:
# 9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами
# в діапазоні від -5 до 5 та знайдіть їх добуток.
mat_p1 = np.random.randint(-5, 6, (3, 3))
mat_p2 = np.random.randint(-5, 6, (3, 3))

print("Матриця 1:\n", mat_p1)
print("Матриця 2:\n", mat_p2)
print("Добуток матриць (dot product):\n", np.dot(mat_p1, mat_p2))

Матриця 1:
 [[-4 -5 -5]
 [-3 -3 -4]
 [-2  2 -2]]
Матриця 2:
 [[4 2 3]
 [2 3 0]
 [0 4 1]]
Добуток матриць (dot product):
 [[-26 -43 -17]
 [-18 -31 -13]
 [ -4  -6  -8]]


In [12]:
# 10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами
# в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
mat_sum = np.random.uniform(-1, 1, (3, 3))
row_sums = np.sum(mat_sum, axis=1).reshape(-1, 1)

print("Матриця:\n", mat_sum)
print("Вектор-стовпчик сум рядків:\n", row_sums)

Матриця:
 [[-2.98855015e-05 -7.49187048e-01 -5.33175856e-01]
 [-2.80056670e-01 -9.97548977e-01 -3.31296240e-02]
 [ 3.62133732e-01  6.58009410e-01 -5.31788966e-01]]
Вектор-стовпчик сум рядків:
 [[-1.28239279]
 [-1.31073527]
 [ 0.48835418]]
